### ISSUE TITLE
Code reference issue

### ISSUE THREAD

**Issue by mccrearyp** [david-a-wheeler/flawfinder#93]
The GitHub action example example shows:
```
- name: flawfinder_scan
  uses: david-a-wheeler/flawfinder@2.0.19
  with:
    arguments: '--sarif ./'
    output: 'flawfinder_results.sarif'
```

Which works, but it prefixes the directories with a "./" which breaks the code referencing in the GitHub security alert. Switching the ./ to a * fixes the issue. So the documentation should be updated to this:

```
- name: flawfinder_scan
  uses: david-a-wheeler/flawfinder@2.0.19
  with:
    arguments: '--sarif *'
    output: 'flawfinder_results.sarif'
```
